#!/usr/bin/env python3

import os
import sys

arg_length = len(sys.argv)
if arg_length != 2:
    print("Invalid number of arguments. Usage: './init MODELNAME'")
    exit(1)

model_name = sys.argv[1]

file_replacements = [
    "constants.py",
    "pyproject.toml",
]

# Handle text replacements
for filename in file_replacements:
    with open(filename) as f:
        replacement = f.read().replace(':model_name', model_name)

    with open(filename, "w") as f:
        f.write(replacement)

# Delete self
os.remove(os.path.basename(__file__))
